os: linux
dist: bionic

language: python
python: 3.7

env:
   - BUILD_SHARED_LIBS=OFF
   - BUILD_SHARED_LIBS=ON

addons:
   apt:
      packages:
      - cmake
      - build-essential
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python3
      - python3-pip
#      - libopenmpi-dev
#      - libscalapack-openmpi-dev

script:
- mkdir _build
- cd _build
- cmake -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} -DBUILD_TESTING=ON ..
- make -j 2 
- ctest -j 2 
